### ISSUE TITLE
Transfer to rescript-lang org

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/create-rescript-app#4]
Hi @mahezsh,

We will be removing the built-in templates ("rescript init") from the ReScript compiler in version 11 as they are completely outdated, see https://github.com/rescript-lang/rescript-compiler/issues/5682.

We would like to keep such functionality (creation of new projects from templates) decoupled from the compiler in the future.

I like the simple approach taken in your create-rescript-app project. Would it be possible to transfer it to the [rescript-lang](https://github.com/rescript-lang) organization so that we can continue maintaining it there, and also give the ReScript team access to the [create-rescript-app npm package](https://www.npmjs.com/package/create-rescript-app)?

**Comment by mahezsh** [comment]
Hi @cknitt,

I tried transferring the repo to rescript-lang but I'm getting _**You don’t have the permission to create public repositories on rescript-lang**_ Could you add me as a member?

Thanks.

**Comment by cknitt** [comment]
@cristianoc @ryyppy How can we handle the repo transfer? I do not have permissions to add members to the rescript-lang org.

@mahezsh For the npm package, could you add me (cknittel), cristianoc and ryyppy?

**Comment by mahezsh** [comment]
@cknitt Have invited 3 of you as maintainers.

**Comment by cknitt** [comment]
Thanks a lot! 👍

**Comment by ryyppy** [comment]
@mahezsh could you give me admin rights for this repo so I can try transfer it to the organization? Need to check if I have enough permissions to do a transfer.

**Comment by mahezsh** [comment]
@ryyppy Done!

**Comment by ryyppy** [comment]
@mahezsh I think I am missing some credentials. I don't see any setting panel... might be that you need to transfer ownership to my account. GitHub's transfer mechanism is confusing.

**Comment by mahezsh** [comment]
@ryyppy I transferred the ownership to your account.

**Comment by ryyppy** [comment]
Thanks. It's now part of the ReScript organization.

**Comment by cknitt** [comment]
@mahezsh @ryyppy Thank you for performing the transfer!
