### ISSUE TITLE
Add .gitignore when creating from Basic template

### ISSUE THREAD

**Issue by DZakh** [rescript-lang/create-rescript-app#52]

**Comment by DZakh** [comment]
In my case it should include:
```
node_modules
lib
```

**Comment by fhammerschmidt** [comment]
There is a gitignore and it contains the folders you suggest. 
https://github.com/rescript-lang/create-rescript-app/blob/master/templates/rescript-template-basic/_gitignore

I just tried creating a project again with npm and pnpm and it correctly copies it over.

**Comment by DZakh** [comment]
Hmm, is that because it used an older version 🤔

**Comment by fhammerschmidt** [comment]
Probably. What version (of create-rescript-app I assume) did you use?

**Comment by fhammerschmidt** [comment]
Closing this, we documented now that you should use `npm create rescript-app@latest`
