### ISSUE TITLE
Basic template doesn't compile out of the box with the @rescript/core option set to no

### ISSUE THREAD

**Issue by DZakh** [rescript-lang/create-rescript-app#54]
<img width="769" alt="image" src="https://github.com/rescript-lang/create-rescript-app/assets/49292466/9e6356f2-6166-46e1-9667-49a2f12cf702">

**Comment by cknitt** [comment]
@DZakh In the current create-rescript-app version, there is no option to disable Core anymore.

What version of create-rescript-app are you running / how did you invoke it?

Note that npm may run an old version when you do `npm create rescript-app`.
Run `npm create rescript-app@latest` to make sure to get the latest one. (That should go into the README I guess.)

![Bildschirmfoto 2024-05-08 um 10 44 46](https://github.com/rescript-lang/create-rescript-app/assets/591384/fc4afa3d-5d14-4c0c-bb8a-8a84ab8cf5e4)

**Comment by DZakh** [comment]
> Note that npm may run an old version when you do npm create rescript-app.

That was probably the case
